name: mac_build_test

on: [ push ]

jobs:
  build_and_test:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure CMake
        shell: bash
        run: cmake -S . -B build -DENABLE_ASAN=ON

      - name: Build
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: cmake --build build -- -j 10

      - name: Run Unit Tests
        shell: bash
        run: |
          cd build
          ctest --verbose

  android_build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e
          add-to-path: false
      - name: Build
        shell: bash
        run: bash ./scripts/android_build.sh
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}